package io.github.coswind.mytwitter.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STATUS.
 */
public class Status {

    private Long id;
    private Long status_id;
    private String jsonString;

    public Status() {
    }

    public Status(Long id) {
        this.id = id;
    }

    public Status(Long id, Long status_id, String jsonString) {
        this.id = id;
        this.status_id = status_id;
        this.jsonString = jsonString;
    }

    public Status(Long status_id, String jsonString) {
        this.status_id = status_id;
        this.jsonString = jsonString;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getStatus_id() {
        return status_id;
    }

    public void setStatus_id(Long status_id) {
        this.status_id = status_id;
    }

    public String getJsonString() {
        return jsonString;
    }

    public void setJsonString(String jsonString) {
        this.jsonString = jsonString;
    }

}
